### ISSUE TITLE
Copyright and License

### ISSUE THREAD

**Issue by will-moore** [ome/cookiecutter-omero-webapp#3]
The generated app should contain the GPL v2 license, same as https://github.com/ome/openmicroscopy/blob/develop/LICENSE.txt
since omero-web (and omero-py) are dependencies.

However, we probably don't want to add any Copyright headers to files (currently we have standard OME copyright dated 2017).

cc @jburel

**Comment by jburel** [comment]
web apps are licensed under AGPL e.g. https://github.com/ome/omero-figure/blob/master/LICENSE
So we may want to include a License file and something
```
#
# Copyright (c) TBD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
```

**Comment by jburel** [comment]
``.gitignore`` should also be included

**Comment by will-moore** [comment]
`.gitignore` is already included, but it does need to be tidied: https://github.com/ome/cookiecutter-omero-webapp/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/.gitignore
