### ISSUE TITLE
cookiecutter.webapp_title not updated in html page

### ISSUE THREAD

**Issue by will-moore** [ome/cookiecutter-omero-webapp#4]
Minor bug:

See https://github.com/will-moore/omero-scriptui/commit/dec8af49daff49b3405f6d72677f940b8297e5a6 which is an example output from this cookiecutter...

The template placeholder `{{cookiecutter.webapp_title}}` in the `<h1>` of the page didn't get updated by cookieicutter when it generated that output, although an identical placeholder in the page `<title>` did work. Not sure why the 2nd was ignored.

**Comment by jburel** [comment]
Fixed by [dcdabb340830373a290173f4ce3d060f9c462610](https://github.com/ome/cookiecutter-omero-webapp/pull/6/commits/dcdabb340830373a290173f4ce3d060f9c462610)
